name: pinwalls
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  get: ^4.6.6
  http: ^1.3.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
